Traceback (most recent call last):
  File "d:\Virtual\PythonLearn\chapter10\chapter10grammar.py", line 31, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
